# Build and deploy ASP.NET Core app to Azure Web App - GotorzProject
name: Build and deploy ASP.Net Core app to Azure Web App - GotorzProject
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
env:
  DOTNET_VERSION: '8.x'
  PUBLISH_DIR: ${{ github.workspace }}/publish
 
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
 
      - name: Restore
        run: dotnet restore
 
      - name: Build
        run: dotnet build --configuration Release --no-restore
 
      - name: Publish
        run: dotnet publish --configuration Release --output "${{ env.PUBLISH_DIR }}" --no-build
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.PUBLISH_DIR }}
 
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ env.PUBLISH_DIR }}
 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F0583DAB2B304F2793E242FB0381F789 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0AA1324E48B24E2DBD85088587EB94AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AC20F7E8088417D94E6799DC35DE923 }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: GotorzProject
          slot-name: Production
          package: ${{ env.PUBLISH_DIR }}
